//
//  Icon.swift
//  Housetainer
//
//  Created by 이주상 on 2023/11/08.
//

import UIKit

struct Icon {
    private init () {}
    static let add = UIImage(named: "icon_add")
    static let addAPhoto = UIImage(named: "icon_add_a_photo")
    static let calendarArrowLeft = UIImage(named: "icon_calendar_left_arr")
    static let calendarArrowRight = UIImage(named: "icon_calendar_right_arr")
    static let arrowRight = UIImage(named: "icon_arr_right_s")
    static let cameraLarge = UIImage(named: "icon_camera_l")
    static let cameraSmall = UIImage(named: "icon_camera_s")
    static let arrowLeft = UIImage(named: "icon_common_arr_l")
    static let close = UIImage(named: "icon_common_close")
    static let link = UIImage(named: "icon_common_link")
    static let dateSmall = UIImage(named: "icon_date_s")
    static let housetainer = UIImage(named: "icon_housetainer")
    static let imageClear = UIImage(named: "icon_img_clear")
    static let inputClear = UIImage(named: "icon_input_clear")
    static let calender = UIImage(named: "icon_main_calendar")
    static let event = UIImage(named: "icon_main_event")
    static let house = UIImage(named: "icon_main_house")
    static let nofaceLarge = UIImage(named: "icon_noface_l")
    static let nofaceS = UIImage(named: "icon_noface_s")
    static let nofaceXS = UIImage(named: "icon_noface_xs")
    static let pickOff = UIImage(named: "icon_pick_off")
    static let pickOn = UIImage(named: "icon_pick_on")
    static let homeTab = UIImage(named: "icon_tabbar_home_inactive")
    static let dateupTab = UIImage(named: "icon_tabbar_dateup_inactive")
    static let myTab = UIImage(named: "icon_tabbar_my_inactive")
    static let homeTabActive = UIImage(named: "icon_tabbar_home_active")
    static let dateupTabActive = UIImage(named: "icon_tabbar_dateup_active")
    static let myTabActive = UIImage(named: "icon_tabbar_my_active")
    static let checkOn = UIImage(named: "icon_check_on")
    static let checkOff = UIImage(named: "icon_check_off")
    static let naver = UIImage(named: "icon_login_naver")
    static let kakao = UIImage(named: "icon_login_kakao")
    static let google = UIImage(named: "icon_login_google")
    static let apple = UIImage(named: "icon_login_apple")
    static let edit = UIImage(named: "icon_more")
    static let arrowUp = UIImage(named: "icon_up_gray_s")
    static let arrowDown = UIImage(named: "icon_down_gray_s")
    static let map = UIImage(named: "icon_map")
    static let invite = UIImage(named: "icon_invite")
    static let bookMarkInactive = UIImage(named: "icon_bookmark_inactive")
    static let bookMarkActive = UIImage(named: "icon_bookmark_active")
    static let checkCircleOn = UIImage(named: "icon_check_circle_on")
    static let checkCircleOff = UIImage(named: "icon_check_circle_off")
    static let checkSquareOn = UIImage(named: "icon_check_square_on")
    static let checkSquareOff = UIImage(named: "icon_check_square_off")
    static let warning = UIImage(named: "icon_warning")
    static let loginLogo = UIImage(named: "icon_new_logo")
    static let alarmOn = UIImage(named: "icon_alarm_on")
    static let alarmOff = UIImage(named: "icon_alarm_off")
    static let savedAlarm = UIImage(named: "icon_saved_alarm")
    static let commentAlarm = UIImage(named: "icon_comment_alarm")
    static let homeletterAlarm = UIImage(named: "icon_homeletter_alarm")
    static let bigAlarm = UIImage(named: "icon_big_alarm")
}
